name: elec3442
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - fastapi>=0.135.2
  - loguru>=0.7.3
  - numpy>=2.4.3
  - pydantic-settings>=2.13.1
  - sqlmodel>=0.0.37
  - uvicorn>=0.42.0
  - opencv>=4.13
  - pip:
      - -e .